
var events = [
    {
        "title":"Opening Call for Paper",
        "date": new Date(2021,6-1,15),
    },
    {
        "title":"Round II : Paper Submission Deadline",
        "date": new Date(2021,9-1,15),
    },
    {
        "title":"Notification of Acceptance ",
        "date": new Date(2021,10-1,5),
    },
    {
        "title":"Submission of Camera Ready Paper ",
        "date": new Date(2021,10-1,15),
    },
    {
        "title":"Author Registration",
        "date": new Date(2021,10-1,20),
    },
    {
        "title":"Conference Begins",
        "date": new Date(2021,10-1,27),
    },

    {
        "name": "Keshav Dahal",
        "isTalk":true,
        "imgurl": "https://research-portal.uws.ac.uk/files-asset/258789/Keshav_photo.jpg?w=160&f=webp",
        "worksAt": "University of the West of Scotland (UWS)U.K",
        "title": "Pre Conference Talk",
        "topic": "Blockchain Characteristics and its Effect in Business Models",
        "bio" : "Professor Keshav Dahal is a Professor of intelligent systems and the director of the Artificial Intelligence, Visual Communications and Network (AVCN) Research Centre, University of the West of Scotland, Paisley, U.K. He received his Masters and Ph.D. degrees from the University of Strathclyde, UK. He also worked at the University of Bradford and the University of Strathclyde. His research interests lie in the areas of applied AI, trust and security modelling in distributed systems, Blockchain technology and scheduling/optimization problems. He has been principle investigator or co-investigators on more than 15 externally funded projects, and supervised over 25 PhD and postdoctoral researchers. He has published over 160 papers in his research fields with award winning publications and has sat on organizing/program committees of over 60 international conferences. He is a Senior Member of IEEE.",
        "abstract":"",
        "date": new Date(2021, 10 - 1, 27),
        "website":"https://research-portal.uws.ac.uk/en/persons/keshav-dahal",

    },
    {
        "name": "Sushil Jajodia",
        "isTalk":true,
        "imgurl": "https://csis.gmu.edu/jajodia/Jajodia.jpg",
        "worksAt": "George Mason University Fairfax",
        "title": "Keynote 1",
        "topic": "Maintaining level of operational effectiveness of a CSOC under adverse conditions",
        "bio" : `Dr. Sushil Jajodia is University Professor, BDM International Professor, and the founding
        director of Center for Secure Information Systems in the College of Engineering and Computing
        at the George Mason University, Fairfax, Virginia. He is also the founding director of the NSF
        IUCRC Center for Cybersecurity Analytics and Automation at Mason.  He has an extensive track
        record in cyber security research and significant leadership experience, having served in various
        leadership roles throughout his career. Dr. Jajodia has authored or coauthored seven books,
        edited 44 books and conference proceedings, and published more than 450 technical papers in
        refereed journals and conference proceedings. He holds several U.S. patents, and has received a
        number of prestigious awards in recognition of his research accomplishments.`,
        "abstract":`In a cybersecurity operations center (CSOC), under normal operating conditions
        in a day, sufficient numbers of analysts are available to analyze the amount of
        alert workload generated by intrusion detection systems (IDSs). This means
        that the cybersecurity analysts can fully investigate each and every alert that is
        generated by the IDSs in a reasonable amount of time. However, there are a
        number of disruptive factors that can adversely impact the normal operating
        conditions such as 1) higher alert generation rates from a few IDSs, 2) new
        alert patterns that decreases the throughput of the alert analysis process, and
        3) analyst absenteeism. The impact of all the above factors is that the alerts
        wait for a long duration before being analyzed, which impacts the readiness of
        the CSOC. It is imperative that the readiness of the CSOC be quantified. In my
        talk, I will describe how this can be quantified, monitored by knowing the exact
        deviation of the CSOC conditions from normal, and how long it takes for the
        condition to return to normal.`,
        "date": new Date(2021, 10 - 1, 28),
        "website":"https://csis.gmu.edu/jajodia",

    },
    {
        "name": "Pierangela Samarati",
        "isTalk":true,
        "imgurl": "https://i.ibb.co/M7gcWLb/pierangelasamarati.jpg",
        "worksAt": "Università degli Studi di Milano, Italy",
        "title": "Keynote 2",
        "topic": "Data security and privacy in emerging scenarios",
        "bio" : `Pierangela Samarati is a Professor at the Department of Computer
        Science of the Università degli Studi di Milano, Italy. Her main
        research interests are on data and applications security and privacy,
        especially in emerging scenarios.  She has been Computer Scientist at
        SRI, CA (USA) and visiting researcher at Stanford University, CA
        (USA), and at George Mason University, VA (USA).  She is the chair of
        the IEEE Systems Council Technical Committee on Security and Privacy
        in Complex Information Systems (TCSPCIS), of the ERCIM Security and
        Trust Management Working Group (STM), and of the ACM Workshop on
        Privacy in the Electronic Society (WPES). She is ACM Distinguished
        Scientist (named 2009) and IEEE Fellow (named 2012).  She has received
        the ESORICS Outstanding Research Award (2018), the IEEE Computer
        Society Technical Achievement Award (2016), the IFIP WG 11.3
        Outstanding Research Contributions Award (2012), and the IFIP TC11
        Kristian Beckman Award (2008).`,
        "abstract":`The rapid advancements in Information and Communication Technologies
        (ICTs) have been greatly changing our society, with clear societal and
        economic benefits. Mobile technology, Cloud, Big Data, Internet of
        things, services and technologies that are becoming more and more
        pervasive and conveniently accessible, towards to the realization of a
        smart society.  At the heart of this evolution is the ability to
        collect, analyze, process and share an ever-increasing amount of data,
        to extract knowledge for offering personalized and advanced
        services. A major concern, and potential obstacle, towards the full
        realization of such evolution is represented by security and privacy
        issues. As a matter of fact, the (actual or perceived) loss of control
        over data and potential compromise of their confidentiality can have a
        strong detrimental impact on the realization of an open framework for
        enabling collection, processing, and sharing of data, typically stored
        or processed by external cloud services. In this talk, I will
        illustrate some security and privacy issues arising in emerging
        scenarios, focusing in particular on the problem of managing data
        while guaranteeing confidentiality and integrity of data stored or
        processed by external providers.`,
        "date": new Date(2021, 10 - 1, 29),
        "website":"http://www.di.unimi.it/samarati/",

    },
    // {
    //     "title": "Keynote 2",
    //     "isTalk":true,
    //     "date": new Date(2021,10-1,29,9,30),
    //     "name" : "Rami Puzis",
    //     "desc" : "Mastering the Social Networks",
    //     "imgurl":"" 
    // },
    // {
    //     "title": "Keynote 3",
    //     "isTalk":true,
    //     "date": new Date(2021,10-1,29,14,30),
    //     "name" : "Rajeev Barua",
    //     "desc" : " Malware Analysis: Beating the Bad Guys",
    //     "imgurl":"" 
    // },
    {
        "title":"Conference Ends",
        "date": new Date(2021,10-1,30),
    },
]
export  default events;