
var events = [
    {
        "title":"Opening Call for Paper",
        "date": new Date(2021,6-1,15),
    },
    {
        "title":"Round I : Paper Submission Deadline",
        "date": new Date(2021,8-1,25),
    },
    {
        "title":"Round II : Paper Submission Deadline",
        "date": new Date(2021,9-1,15),
    },
    {
        "title":"Notification of Acceptance of Round I",
        "date": new Date(2021,9-1,20),
    },
    {
        "title":"Notification of Acceptance of Round II",
        "date": new Date(2021,10-1,20),
    },
    {
        "title":"Submission of Camera Ready Paper",
        "date": new Date(2021,9-1,30),
    },
    {
        "title":"Author Registration",
        "date": new Date(2021,10-1,15),
    },
    {
        "title":"Conference Begins",
        "date": new Date(2021,10-1,27),
    },

    {
        "name": "Keshav Dahal",
        "isTalk":true,
        "imgurl": "https://research-portal.uws.ac.uk/files-asset/258789/Keshav_photo.jpg?w=160&f=webp",
        "worksAt": "University of the West of Scotland (UWS)U.K",
        "title": "Pre Conference Talk",
        "topic": "Blockchain Characteristics and its Effect in Business Models",
        "bio" : "Professor Keshav Dahal is a Professor of intelligent systems and the director of the Artificial Intelligence, Visual Communications and Network (AVCN) Research Centre, University of the West of Scotland, Paisley, U.K. He received his Masters and Ph.D. degrees from the University of Strathclyde, UK. He also worked at the University of Bradford and the University of Strathclyde. His research interests lie in the areas of applied AI, trust and security modelling in distributed systems, Blockchain technology and scheduling/optimization problems. He has been principle investigator or co-investigators on more than 15 externally funded projects, and supervised over 25 PhD and postdoctoral researchers. He has published over 160 papers in his research fields with award winning publications and has sat on organizing/program committees of over 60 international conferences. He is a Senior Member of IEEE.",
        "abstract":"",
        "date": new Date(2021, 10 - 1, 27),
        "website":"https://research-portal.uws.ac.uk/en/persons/keshav-dahal",

    },
    {
        "name": "Sushil Jajodia",
        "isTalk":true,
        "imgurl": "https://csis.gmu.edu/jajodia/Jajodia.jpg",
        "worksAt": "George Mason University Fairfax",
        "title": "Keynote 1",
        "topic": "Maintaining level of operational effectiveness of a CSOC under adverse conditions",
        "bio" : `Dr. Sushil Jajodia is University Professor, BDM International Professor, and the founding
        director of Center for Secure Information Systems in the College of Engineering and Computing
        at the George Mason University, Fairfax, Virginia. He is also the founding director of the NSF
        IUCRC Center for Cybersecurity Analytics and Automation at Mason.  He has an extensive track
        record in cyber security research and significant leadership experience, having served in various
        leadership roles throughout his career. Dr. Jajodia has authored or coauthored seven books,
        edited 44 books and conference proceedings, and published more than 450 technical papers in
        refereed journals and conference proceedings. He holds several U.S. patents, and has received a
        number of prestigious awards in recognition of his research accomplishments.`,
        "abstract":`In a cybersecurity operations center (CSOC), under normal operating conditions
        in a day, sufficient numbers of analysts are available to analyze the amount of
        alert workload generated by intrusion detection systems (IDSs). This means
        that the cybersecurity analysts can fully investigate each and every alert that is
        generated by the IDSs in a reasonable amount of time. However, there are a
        number of disruptive factors that can adversely impact the normal operating
        conditions such as 1) higher alert generation rates from a few IDSs, 2) new
        alert patterns that decreases the throughput of the alert analysis process, and
        3) analyst absenteeism. The impact of all the above factors is that the alerts
        wait for a long duration before being analyzed, which impacts the readiness of
        the CSOC. It is imperative that the readiness of the CSOC be quantified. In my
        talk, I will describe how this can be quantified, monitored by knowing the exact
        deviation of the CSOC conditions from normal, and how long it takes for the
        condition to return to normal.`,
        "date": new Date(2021, 10 - 1, 28),
        "website":"https://csis.gmu.edu/jajodia",

    },
    {
        "name": "Will be Updated Soon",
        "isTalk":true,
        "imgurl": "",
        "worksAt": "Will be Updated Soon",
        "title": "Keynote 2",
        "topic": "Will be Updated Soon",
        "bio" : "Will be Updated Soon",
        "abstract":"",
        "date": new Date(2021, 10 - 1, 29),
        "website":"",

    },
    // {
    //     "title": "Keynote 2",
    //     "isTalk":true,
    //     "date": new Date(2021,10-1,29,9,30),
    //     "name" : "Rami Puzis",
    //     "desc" : "Mastering the Social Networks",
    //     "imgurl":"" 
    // },
    // {
    //     "title": "Keynote 3",
    //     "isTalk":true,
    //     "date": new Date(2021,10-1,29,14,30),
    //     "name" : "Rajeev Barua",
    //     "desc" : " Malware Analysis: Beating the Bad Guys",
    //     "imgurl":"" 
    // },
    {
        "title":"Conference Ends",
        "date": new Date(2021,10-1,30),
    },
]
export  default events;